FROM python:3.11.1-slim

WORKDIR /code

COPY ./assignment5 ./assignment5

RUN pip install --no-cache-dir -r ./assignment5/requirements.txt

CMD [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]